### ISSUE TITLE
Blank/grey world on v0.4.

### ISSUE THREAD

**Issue by ghost** [GuilhermeRossato/3D-Redstone-Simulator#4]
Hi there, I really like your work on this project. I tried downloading version 0.4 to try out the procedural generation, however I am presented with a blank/grey screen, but I do get the hotbar and menu. 

Here's an image: [http://i.imgur.com/ETKeksz.png](url)

**Comment by GuilhermeRossato** [comment]
Hi, Thanks.

There's a bug when not loading a valid cookie that makes you load a rotation of NaN which propagates to a quartenion used by velocity, in the end all your positions axes are NaN, which makes you teleport to a this gray nothing-ness.

Your current position can be displayed in the console by:
`player.controls.player.position;`

(A bit redundant, I know, but that was fixed in newer versions)

To fix your problem, you must run the following in the console (F12):

```javascript
	camera.parent.position.set(0,0,0)
	camera.parent.rotation.set(0,0,0)
	camera.parent.parent.position.set(0,0,0)
	camera.parent.parent.rotation.set(0,0,0)
	player.controls.player.position.set(0,15,0)
```

If you want to fix it forever, you must change from line 127 of Script/Classes/Controls/MinecraftControls.js:

```javascript
	if (x && y && (!isNaN(parseFloat(x))) && (!isNaN(parseFloat(y)))) {
		this.pitch.rotation.set(parseFloat(x), 0, 0);
		this.player.rotation.set(0, parseFloat(y), 0);
	} else {
		this.pitch.rotation.set(options.defaultRotation.pitch,0 ,0);
		this.player.rotation.set(0, options.defaultRotation.yaw, 0);
	}
```
